services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_GTM: ${NEXT_PUBLIC_GTM:-}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-}
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3005:3000"
    env_file:
      - .env
